version: "3"
services:
  www:
    build:
      context: ./apache-php
      args:
        - WITH_XDEBUG=${WITH_XDEBUG}
    ports:
      - ${HTTP_PORT}:80
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: "remote_host=localhost remote_connect_back=1"
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./www:/var/www/html
      - ./apache2:/var/log/apache2
    links:
      - db
    networks:
      - default
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d:rw
      - ./storage:/var/lib/mysql:rw
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - ${PHP_ADMIN_PORT}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  persistent:

networks:
  default:
    driver: bridge
